name:                monadic-games-club
version:             0.1.0.0
homepage:            https://github.com/silky/monadic-games-club
license:             OtherLicense
extra-source-files:
- README.md

dependencies:
  - base >= 4.15 && < 4.19
  - text
  - crem
  - singletons-base

language:
  GHC2021

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstrainedClassMethods
  - ConstraintKinds
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyCase
  - EmptyDataDecls
  - EmptyDataDeriving
  - ExistentialQuantification
  - ExplicitForAll
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - GADTSyntax
  - GeneralisedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitPrelude
  - ImportQualifiedPost
  - InstanceSigs
  - KindSignatures
  - MonomorphismRestriction
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NamedWildCards
  - NumericUnderscores
  - PatternGuards
  - PolyKinds
  - PostfixOperators
  - RankNTypes
  - RelaxedPolyRec
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - StarIsType
  - TraditionalRecordSyntax
  - TupleSections
  - TypeApplications
  - TypeOperators
  - TypeSynonymInstances
  - PackageImports
  - DerivingStrategies

ghc-options:
  # Enable every warning GHC supports
  - -Weverything                   # https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Weverything

  # Turn off the warnings we don't care about.
  - -Wno-safe                      # https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/safe_haskell.html#ghc-flag--Wsafe
  - -Wno-unsafe                    # https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/safe_haskell.html#ghc-flag--Wunsafe
  - -Wno-missing-safe-haskell-mode # https://downloads.haskell.org/ghc/latest/docs/users_guide/exts/safe_haskell.html#ghc-flag--Wmissing-safe-haskell-mode
  - -Wno-implicit-prelude          # https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wimplicit-prelude
  - -Wno-missing-export-lists      # https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wmissing-export-lists
  - -Wno-missing-home-modules      # https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wmissing-home-modules
  - -Wno-missing-import-lists      # https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wmissing-import-lists
  - -Wno-all-missed-specialisations    # https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wall-missed-specialisations
  - -Wno-prepositive-qualified-module  # https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wprepositive-qualified-module
# https://downloads.haskell.org/ghc/latest/docs/users_guide/using-warnings.html#ghc-flag--Wmissing-kind-signatures
- -Wno-missing-kind-signatures

library:
  source-dirs: src
