name:                monadic-games-club
version:             0.1.0.0
homepage:            https://github.com/silky/monadic-games-club
license:             OtherLicense
extra-source-files:
  - README.md

dependencies:
  - base >= 4.15 && < 4.19
  - crem

language:
  GHC2021

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveLift
  - DerivingStrategies
  - DerivingVia
  - LambdaCase
  - PackageImports
  - TypeFamilies
  - OverloadedStrings

ghc-options:
  # Enable every warning GHC supports
  - -Weverything

  # Turn off the warnings we don't care about.
  - -Wno-all-missed-specialisations
  - -Wno-implicit-prelude
  - -Wno-missing-export-lists
  - -Wno-missing-home-modules
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-missed-specialisations

  # Bring back one day
  - -Wno-unused-packages

library:
  source-dirs: src
  dependencies:
    - aeson
    # - bytestring
    - containers
    - elm-street
    - extra
    - singletons-base
    - text

executables:
  generate-elm-types:
    source-dirs: generate-elm-types
    main: Main.hs
    dependencies:
      - elm-street
      - monadic-games-club

  skulls-game-server:
    source-dirs: skulls-game-server
    main: Main.hs
    dependencies:
      - aeson
      - monadic-games-club
      - servant
      - servant-server
      - servant-websockets
      # - text
      - wai
      - warp
      - websockets

tests:
  monadic-games-club-spec:
    main:           Spec.hs
    source-dirs:    spec
    dependencies:
      - monadic-games-club
      - hspec
    build-tools: hspec-discover:hspec-discover
