name:                monadic-games-club
version:             0.1.0.0
homepage:            https://github.com/silky/monadic-games-club
license:             OtherLicense
extra-source-files:
- README.md

dependencies:
  - base >= 4.15 && < 4.19
  - text
  - crem
  - singletons-base

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - NamedFieldPuns
  - OverloadedStrings
  - PackageImports
  - ScopedTypeVariables
  - StandaloneDeriving
  - StandaloneKindSignatures
  - TypeApplications
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
